package sdk_test

const Lipsum = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi varius orci ac velit commodo, in maximus orci rhoncus. Sed sollicitudin neque magna, vitae lacinia leo porttitor eget. Integer ullamcorper, ipsum in pharetra volutpat, enim elit tincidunt metus, at varius dolor neque sed risus. Aenean facilisis euismod posuere. Suspendisse potenti. Duis tristique tincidunt sem, sit amet porta metus maximus eu. Nam dictum nunc eu lectus convallis interdum. Vivamus ac neque ac mi finibus tincidunt. Curabitur tempus mauris id diam tempus blandit. Donec a bibendum ex. Morbi mi nulla, faucibus ut blandit vitae, bibendum ullamcorper leo. Morbi feugiat eget ante vitae tincidunt. Etiam elit tellus, vehicula at maximus sed, bibendum nec mi. Ut porttitor efficitur facilisis.

In hac habitasse platea dictumst. Aliquam venenatis massa eros, accumsan malesuada nibh commodo sit amet. Aliquam non auctor ante, non tincidunt dui. Morbi tincidunt orci non mi convallis faucibus. Maecenas lobortis ultricies bibendum. Phasellus dolor enim, efficitur sit amet ullamcorper et, feugiat eu ligula. Donec ac purus nunc. Nam viverra at eros vitae aliquet. Mauris non efficitur augue. Aliquam commodo augue efficitur nisl mattis, nec vulputate risus rutrum. Pellentesque gravida id velit efficitur semper.

Integer eu ultrices sem, egestas finibus lorem. Aenean ultricies molestie tortor. Proin ligula lorem, pretium ac nisi vel, mollis sagittis tortor. Etiam pretium ex at magna condimentum efficitur. Etiam eu aliquam urna, et tempus elit. Nulla laoreet neque non mollis pulvinar. Vivamus at erat ante. Donec fringilla odio sit amet bibendum maximus. Donec eget arcu sed neque elementum venenatis sed eget lorem. Morbi rutrum nisi tortor, id tempus lectus viverra id. Nulla libero est, rhoncus et ultrices in, aliquam ut augue. Cras pretium eleifend ligula non rhoncus.

Donec hendrerit lacus vel eros suscipit, non pretium nisl luctus. Proin ultricies, ex vitae mollis pulvinar, nunc nibh volutpat purus, nec tristique tellus metus sed odio. Cras efficitur massa sed est euismod, vitae tristique risus varius. Duis suscipit facilisis nisi, vitae varius ante pretium id. Phasellus ut suscipit dui. Aenean tincidunt nunc mi, et mattis ligula luctus eu. Pellentesque fringilla nunc tortor, ut finibus massa auctor sed. Fusce laoreet gravida varius. Aenean congue lectus et pretium sollicitudin. Cras massa diam, tempus sed risus ut, luctus suscipit tellus.

Donec vehicula egestas vulputate. Etiam venenatis rutrum ante, a interdum nunc aliquam non. Donec venenatis lectus eu ligula interdum aliquet. Praesent a pretium neque, ut pharetra ipsum. Praesent egestas dui eget malesuada placerat. Duis quis turpis volutpat, accumsan magna vitae, dignissim nunc. Sed eleifend porta pretium. Nunc vulputate enim in consectetur luctus. Praesent egestas mi et lorem posuere lobortis. Etiam pharetra sollicitudin metus in egestas. Sed accumsan venenatis ex, a fringilla massa auctor id. Nulla rutrum suscipit dui eget finibus. Integer vel luctus ex. Nullam ullamcorper ac velit vel ultricies. Aenean pulvinar dolor eget lectus placerat, ac pulvinar neque congue. Suspendisse vitae quam euismod, fermentum quam in, tristique est.
`
